/**
 * audio.ts — Central config for EVERY sound: music bed, SFX, and per-scene VO.
 *
 * ┌──────────────────────────────────────────────────────────────────────┐
 * │  SWAP-IN: replace the silent placeholders in public/assets/audio/.    │
 * │  • Voice-over: run `npm run vo` (scripts/generate-vo.mjs) with an      │
 * │    ELEVENLABS_API_KEY to fill public/assets/audio/vo/<sceneId>.mp3.    │
 * │  • Music/SFX: drop your licensed files in and keep the filenames       │
 * │    (or update the paths here).                                         │
 * └──────────────────────────────────────────────────────────────────────┘
 */
import {staticFile} from 'remotion';

const dir = 'assets/audio';

export const AUDIO = {
  music: staticFile(`${dir}/music-bed.wav`), // TODO(audio): licensed cinematic-electronic track
  sfx: {
    whoosh: staticFile(`${dir}/sfx/whoosh.wav`),
    click: staticFile(`${dir}/sfx/click.wav`),
    pop: staticFile(`${dir}/sfx/pop.wav`),
    type: staticFile(`${dir}/sfx/type.wav`),
    success: staticFile(`${dir}/sfx/success.wav`),
    notify: staticFile(`${dir}/sfx/notify.wav`),
    swipe: staticFile(`${dir}/sfx/swipe.wav`),
  },
} as const;

/** Per-scene voice-over file (generated by scripts/generate-vo.mjs). */
export const voPath = (sceneId: string) => staticFile(`${dir}/vo/${sceneId}.wav`);

export type SfxName = keyof typeof AUDIO.sfx;

/** Master mix levels (0..1). Music stays low so it never covers narration. */
export const MIX = {
  music: 0.22,
  vo: 1.0,
  whoosh: 0.7,
  click: 0.5,
  pop: 0.55,
  type: 0.4,
  success: 0.7,
  notify: 0.65,
  swipe: 0.5,
} as const;

/** Master switch — set false to preview pure motion with no audio. */
export const SOUND_ENABLED = true;
